[package]
name = "gof1"
version = "0.1.0"
authors = ["SÃ©bastien Baert"]
edition = "2021"

[dependencies]
ggez = "0.9.3"
rand = "0.9.2"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }